
-- #######################################################################################
-- (not rly )AUTOGENERATED HYPRLAND CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf


-- ################
-- ### MONITORS ###
-- ################

-- See https://wiki.hyprland.org/Configuring/Monitors/
hl.monitor({ 
    output = "eDP-1",
    mode = "1920x1080@144",
    position = "0x0", 
    scale = 1
})
hl.monitor({ 
    output = "HDMI-A-1",
    mode = "1920x1080@180",
    position = "1920x0",
    scale = 1
})

-- mirror the laptop (first) display:
-- hl.monitor({
--     output = "",
--     mode = "preferred",
--     position = "auto",
--     scale = 1,
--     mirror = "eDP-1"
-- })


-- ###################
-- ### MY PROGRAMS ###
-- ###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"
local fileManager = "thunar"
local menu = "wofi -S drun"
local browser = "floorp"

-- NOTE: in wofi, the I tag includes images for apps.



-- #################
-- ### AUTOSTART ###
-- #################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:


hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprpaper & mako & waybar & brightnessctl s 50%")
end)

-- previously brightnessctl would be set to 60%.

-- #############################
-- ### ENVIRONMENT VARIABLES ###
-- #############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_THEME","Koishi")
hl.env("XCURSOR_SIZE","32")
hl.env("HYPRCURSOR_THEME","hyprKoishi")
hl.env("HYPRCURSOR_SIZE","32")
hl.env("TERM","kitty")
hl.env("Terminal","kitty -1 --hold")

-- hl.env("GTK_IM_MODULE","wayland")
-- hl.env("GTK_IM_MODULE","")
hl.env("DefaultIMModule","fcitx")
hl.env("XMODIFIERS","@im=fcitx")
hl.env("XMODIFIER","@im=fcitx")
hl.env("GTK_IM_MODULE","fcitx")
hl.env("QT_IM_MODULE","fcitx")
hl.env("GLFW_IM_MODULE","ibus")
hl.env("QT_STYLE_OVERRIDE","kvantum")
hl.env("QT_QPA_PLATFORMTHEME","kde")
hl.env("QT_QPA_PLATFORMTHEME","qt5ct")
hl.env("GTK_THEME","Catppuccin-Mocha-Standard-Flamingo-Dark")
hl.env("XDG_CURRENT_DESKTOP","Hyprland")
hl.env("XDG_SESSION_TYPE","wayland")
hl.env("XDG_SESSION_DESKTOP","Hyprland")
-- hl.env("MOZ_DBUS_REMOTE","1")
hl.env("MOZ_ENABLE_WAYLAND","1")


-- #####################
-- ### LOOK AND FEEL ###
-- #####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 13,
    
        border_size = 2, 

        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = { colors = {"rgba(585b70ee)", "rgba(f5c2e7ee)"}, angle = 90 },
            inactive_border = "rgba(1e1e2eee)",
        },
 
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
    
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
    
        layout = "master",
        -- dwindle = i3 like?
        -- master = dwm like (includes a stack)
    },

    -- https://wiki.hyprland.org/Configuring/Variables/#decoration

    decoration = {
        rounding = 0,
        rounding_power = 0,
    
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
    
        shadow = {
            enabled = true,
            range = 0,
            render_power = 1,
            offset = {5, 5},
            color = "rgba(313244aa)",
            color_inactive = "rgba(11111bbb)",
        },
    
        -- https://wiki.hyprland.org/Configuring/Variables/#blur

        blur = {
            enabled = true,
            size = 4,
            passes = 1, 

            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
    
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
})
-- https://wiki.hyprland.org/Configuring/Variables/#animations

-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1}, {0.32, 1} } })
-- hl.curve("easeOutQuinty", { type = "bezier", points = { {0.23, 1}, {0.32, 1.05} } })
hl.curve("easeOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0}, {0.1, 1} } })
hl.curve("overshot", { type = "bezier", points = { {0.22, 0.99}, {0.23, 1.03} } })
-- hl.curve("ease", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.2, bezier = "easeOutQuint", style = "popin 89%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.69, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.78, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.53, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4.3, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 4.3, bezier = "overshot", style = "slide bottom" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 4.3, bezier = "overshot", style = "slide top" })


-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.

-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        -- pseudotile = true, -- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc
hl.config({
    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true,
    },
})


-- #############
-- ### INPUT ###
-- #############

-- https://wiki.hyprland.org/Configuring/Variables/#input
hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:escape",
        kb_rules = "",
    
        follow_mouse = 1,
    
        sensitivity = -0.305, -- -1.0 - 1.0, 0 means no modification.
    
        accel_profile = "flat",
    
        touchpad = {
            -- disable_while_typing = false,
            tap_to_click = false,
            clickfinger_behavior = true,
            scroll_factor = 0.7,
            natural_scroll = true,
            -- sensitivity = 0,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures
-- hl.gesture({
--     -- workspace_swipe = false
-- })

-- Example per-device config
-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "opentabletdriver-virtual-artist-tablet",
    output = "HDMI-A-1",
})


-- ###################
-- ### KEYBINDINGS ###
-- ###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- local mainMod = "SUPER" -- Sets "Windows" key as main modifier
-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind("SUPER" .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER" .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER" .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind("SUPER" .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER" .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER" .. " + R", hl.dsp.exec_cmd(menu))
hl.bind("SUPER" .. " + P", hl.dsp.window.pseudo())
hl.bind("SUPER" .. " + J", hl.dsp.layout("togglesplit")) -- only applies to dwindle. i use master.
hl.bind("SUPER" .. " + F", hl.dsp.exec_cmd(browser))

hl.bind("SUPER" .. " + PRINT", hl.dsp.exec_cmd("hyprshot --freeze -m output --clipboard-only"))
hl.bind("" .. " + PRINT", hl.dsp.exec_cmd("hyprshot --freeze -m region --clipboard-only"))
hl.bind("SUPER" .. " + CTRL + PRINT", hl.dsp.exec_cmd("hyprshot --freeze -m output --output-folder ~/Downloads/"))
hl.bind("" .. " + CTRL + PRINT", hl.dsp.exec_cmd("hyprshot --freeze -m region --output-folder ~/Downloads/"))

hl.bind("ALT" .. " + Q", hl.dsp.window.close())
hl.bind("ALT" .. " + CTRL + Q", hl.dsp.window.kill())
hl.bind("SUPER" .. " + K", hl.dsp.exec_cmd("hyprctl kill"))

hl.bind("SUPER" .. " + F1", hl.dsp.exec_cmd("hyprctl keyword general:layout dwindle"))
hl.bind("SUPER" .. " + F2", hl.dsp.exec_cmd("hyprctl keyword general:layout master"))
hl.bind("SUPER" .. " + SHIFT + F", hl.dsp.window.fullscreen( { mode = "fullscreen", action = "toggle" } ))

-- #### IMPORTANT HYPRSHOT THING #### https://github.com/Gustash/Hyprshot/issues/60
-- old: layerrule = match:namespace selection, no_anim on
hl.layer_rule {
    name = 'no-anim-for-selection',
    match = { namespace = 'selection' },
    no_anim = true,
}
-- old, convert later:
-- removes cursor from screenshot selection box:
-- cursor {
--     no_hardware_cursors = false
--     -- alternatively, use:
--     -- hide_on_key_press = true
-- }

-- Move focus with mainMod + arrow keys

hl.bind("SUPER" .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER" .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER" .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER" .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER" .. " + ALT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER" .. " + ALT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER" .. " + ALT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER" .. " + ALT + down", hl.dsp.window.move({ direction = "down" }))

hl.bind("SUPER" .. " + Grave", hl.dsp.window.cycle_next({ true }))
hl.bind("SUPER" .. " + SHIFT + Grave", hl.dsp.window.cycle_next({ false }))
hl.bind("SUPER" .. " + ALT + Grave", hl.dsp.window.swap({ direction = "right" })) -- unsure if this works.
hl.bind("SUPER" .. " + ALT + SHIFT + Grave", hl.dsp.window.swap({ direction = "left" })) -- unsure if this works either

hl.bind("SUPER" .. " + CTRL + left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }))
hl.bind("SUPER" .. " + CTRL + right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }))
hl.bind("SUPER" .. " + CTRL + up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }))
hl.bind("SUPER" .. " + CTRL + down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind("SUPER" .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER" .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind("SUPER" .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER" .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind("SUPER" .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER" .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind("SUPER" .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER" .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 10%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- ##############################
-- ### WINDOWS AND WORKSPACES ###
-- ##############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
-- pre 0.53:
-- windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
-- post 0.53:
hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    name = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move = "20 monitor_h-120",
    float = true,
})
